'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

class Solution:
    def findTheDifference(self, s, t):
        if not s and not t:
            return None
        if not s and t:
            return t
        char_freq = {}
        for c in s:
            if c in char_freq:
                char_freq[c] += 1
            else:
                char_freq[c] = 1
        for c in t:
            if c not in char_freq:
                return c
            else:
                char_freq[c] -= 1
                if char_freq[c] < 0:
                    return c
            
sol = Solution()
s = 'abcd'
t = 'abcde'
print(f'Input: {s}, {t}')
print(f'Output: {sol.findTheDifference(s,t)}')
